### PR TITLE
gcp - get dns project resource, fix test fligts names

### PR DESCRIPTION
**Pull request by alexkarpitski**
Use the same approach as there:
#19

### CODE REVIEW

**Comment by jondavidi** [comment]
are these able to still be used without the `resources()` method defined? This is something I raised awhile back in a PR but never heard back on

**Comment by alexkarpitski** [comment]
> are these able to still be used without the `resources()` method defined? This is something I raised awhile back in a PR but never heard back on

@jondavidi, they are available at least for auditing as described there:
https://github.com/cloud-custodian/cloud-custodian/issues/3822

**Comment by jondavidi** [comment]
@alexkarpitski I looked at the link but I still don't understand for the description what exactly that means to be used for audit. here is what it says:

> The current implementation does not allow implement only to get action but application use it for audit.

Can you elaborate on what that means, and who is saying it is a valid use-case for audit purposes (e.g. who's auditing context are we talking about exactly?)

**Comment by alexkarpitski** [comment]
@jondavidi, please take a look at `ApiAuditMode` in [policy.py](https://github.com/mediapills/cloud-custodian/blob/master/tools/c7n_gcp/c7n_gcp/policy.py). When the application is deployed serverlessly, it monitors audit logs and works with resources by resolving them from the log entires. As can be seen, `get_resource()` from [query.py](https://github.com/mediapills/cloud-custodian/blob/master/tools/c7n_gcp/c7n_gcp/query.py) is invoked there and looks like this :

`self.resource_type.get(self.get_client(), resource_info)`

which is supposed to work fine without the `resources()` method defined.

As far as the use cases, [a returned project resource](https://cloud.google.com/dns/docs/reference/v1beta2/projects#resource) can give comprehensive information about DNS quotas allowing to use them for meeting the limits monitoring.

**Comment by jondavidi** [comment]
@alexkarpitski have you ran this with a breakpoint on the function to make sure it's not being called inadvertently somewhere, and verified that it does work with the audit mode for a real policy as you've indicated?

**Comment by alexkarpitski** [comment]
@jondavidi, aborting this one as https://github.com/cloud-custodian/cloud-custodian/issues/3822 has been closed in favor of another approach.

**Comment by jondavidi** [comment]
@alexkarpitski can you update the Jira ticket for this as it's still saying this PR needs review. Thank you

**Comment by alexkarpitski** [comment]
@jondavidi, sure, updated the ticket, sorry for the delay.

**Pull request closed without merging**
